language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-head

before_install: gem update --remote bundler && bundle --version
install:
  - bundle install --retry=3

script:
  - bundle exec rspec
  - PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} bundle exec pronto run -f github_status github_pr -c origin/master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
