language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-head

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install:
  - bundle install --retry=3

script:
  - bundle exec rspec
  - bundle exec rubocop

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
